=== prashg28/XML-Schema-and-Xquery/company.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2015 sp1 (http://www.altova.com) by prashanth (USC) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="Company">
		<xs:annotation>
			<xs:documentation>Comapny XYZ</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Department" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="deptName" type="xs:string"/>
							<xs:element name="deptAddr" type="xs:string"/>
							<xs:element name="Division" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="divName" type="xs:string"/>
										<xs:element name="divPhone" type="xs:string"/>
									</xs:sequence>
									<xs:attribute name="divId" type="xs:string" use="required"/>
									<xs:attribute name="managerEmpId" type="xs:string" use="required"/>
									<xs:attribute name="housedDeptId" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="deptId" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="[A-Z][A-Z][A-Z]"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="Employee" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="empName" type="xs:string"/>
							<xs:element name="empPhone" minOccurs="0">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="[1-9][0-9]{2}\-[0-9]{3}\-[0-9]{4}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="empOffice" type="xs:string"/>
							<xs:element name="WorksFor" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="percentTime" type="xs:integer"/>
									</xs:sequence>
									<xs:attribute name="divId" type="xs:string" use="required"/>
									<xs:attribute name="empId" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="empId" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string"/>
		</xs:complexType>
		<xs:key name="PK_deptId">
			<xs:selector xpath="Department"/>
			<xs:field xpath="@deptId"/>
		</xs:key>
		<xs:key name="PK_empid">
			<xs:selector xpath="Employee"/>
			<xs:field xpath="@empId"/>
		</xs:key>
		<xs:key name="PK_deptId_empId">
			<xs:selector xpath="Employee/WorksFor"/>
			<xs:field xpath="@empId"/>
			<xs:field xpath="@divId"/>
		</xs:key>
		<xs:key name="PK_divId">
			<xs:selector xpath="Department/Division"/>
			<xs:field xpath="@divId"/>
		</xs:key>
		<xs:keyref name="FK_empid" refer="PK_empid">
			<xs:selector xpath="Department/Division"/>
			<xs:field xpath="@managerEmpId"/>
		</xs:keyref>
		<xs:keyref name="FK_housedDeptID" refer="PK_deptId">
			<xs:selector xpath="Department/Division"/>
			<xs:field xpath="@housedDeptId"/>
		</xs:keyref>
		<xs:keyref name="FK_dname" refer="PK_divId">
			<xs:selector xpath="Employee/WorksFor"/>
			<xs:field xpath="@divId"/>
		</xs:keyref>
		<xs:keyref name="FK_ssn" refer="PK_empid">
			<xs:selector xpath="Employee/WorksFor"/>
			<xs:field xpath="@empId"/>
		</xs:keyref>
	</xs:element>
</xs:schema>

=== prashg28/XML-Schema-and-Xquery/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2015 sp1 (http://www.altova.com)-->
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="String" xsi:noNamespaceSchemaLocation="company.xsd">
	<Department deptId="ADM">
		<deptName>Admin</deptName>
		<deptAddr>LA</deptAddr>
		<Division divId="div1" managerEmpId="4" housedDeptId="ADM">
			<divName>HR</divName>
			<divPhone>346-232-3242</divPhone>
		</Division>
		<Division divId="div2" managerEmpId="1" housedDeptId="ADM">
			<divName>Recruitment</divName>
			<divPhone>346-232-3243</divPhone>
		</Division>
		<Division divId="div3" managerEmpId="3" housedDeptId="ADM">
			<divName>SysAd</divName>
			<divPhone>346-232-3244</divPhone>
		</Division>
	</Department>
	<Department deptId="FIN">
		<deptName>Finance</deptName>
		<deptAddr>LA</deptAddr>
		<Division divId="div4" managerEmpId="5" housedDeptId="FIN">
			<divName>Payroll</divName>
			<divPhone>346-232-3245</divPhone>
		</Division>
		<Division divId="div5" managerEmpId="5" housedDeptId="FIN">
			<divName>Accounting</divName>
			<divPhone>346-232-3246</divPhone>
		</Division>
	</Department>
	<Department deptId="SER">
		<deptName>Services</deptName>
		<deptAddr>LA</deptAddr>
		<Division divId="div6" managerEmpId="2" housedDeptId="SER">
			<divName>Networking</divName>
			<divPhone>346-232-3247</divPhone>
		</Division>
		<Division divId="div7" managerEmpId="2" housedDeptId="SER">
			<divName>SaaS</divName>
			<divPhone>346-232-3248</divPhone>
		</Division>
		<Division divId="div8" managerEmpId="1" housedDeptId="SER">
			<divName>Security</divName>
			<divPhone>346-232-3249</divPhone>
		</Division>
		<Division divId="div9" managerEmpId="1" housedDeptId="SER">
			<divName>Convergence</divName>
			<divPhone>346-232-3250</divPhone>
		</Division>
	</Department>
	<Department deptId="OPR">
		<deptName>Operations</deptName>
		<deptAddr>LA</deptAddr>
		<Division divId="div10" managerEmpId="1" housedDeptId="OPR">
			<divName>Sales</divName>
			<divPhone>346-232-3251</divPhone>
		</Division>
		<Division divId="div11" managerEmpId="4" housedDeptId="OPR">
			<divName>Marketing</divName>
			<divPhone>346-232-3252</divPhone>
		</Division>
		<Division divId="div12" managerEmpId="4" housedDeptId="OPR">
			<divName>Engineering</divName>
			<divPhone>346-232-3253</divPhone>
		</Division>
	</Department>
	<Department deptId="BUS">
		<deptName>Business</deptName>
		<deptAddr>LA</deptAddr>
		<Division divId="div13" managerEmpId="1" housedDeptId="BUS">
			<divName>Business Development</divName>
			<divPhone>346-232-3254</divPhone>
		</Division>
		<Division divId="div14" managerEmpId="1" housedDeptId="BUS">
			<divName>Business Analysis</divName>
			<divPhone>346-232-3255</divPhone>
		</Division>
	</Department>
	<Employee empId="1">
		<empName>PSmith</empName>
		<empPhone>243-235-3253</empPhone>
		<empOffice>LA</empOffice>
		<WorksFor divId="div2" empId="1">
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor divId="div3" empId="1">
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor divId="div6" empId="1">
			<percentTime>15</percentTime>
		</WorksFor>
		<WorksFor divId="div8" empId="1">
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor divId="div10" empId="1">
			<percentTime>60</percentTime>
		</WorksFor>
		<WorksFor divId="div13" empId="1">
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor divId="div9" empId="1">
			<percentTime>3</percentTime>
		</WorksFor>
		<WorksFor divId="div14" empId="1">
			<percentTime>2</percentTime>
		</WorksFor>
	</Employee>
	<Employee empId="2">
		<empName>Wong</empName>
		<empPhone>224-234-9065</empPhone>
		<empOffice>LA</empOffice>
		<WorksFor divId="div2" empId="2">
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor divId="div3" empId="2">
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor divId="div6" empId="2">
			<percentTime>30</percentTime>
		</WorksFor>
		<WorksFor divId="div7" empId="2">
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor divId="div1" empId="2">
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor divId="div8" empId="2">
			<percentTime>15</percentTime>
		</WorksFor>
		<WorksFor divId="div4" empId="2">
			<percentTime>15</percentTime>
		</WorksFor>
	</Employee>
	<Employee empId="3">
		<empName>Jack</empName>
		<empPhone>243-235-4566</empPhone>
		<empOffice>LA</empOffice>
		<WorksFor divId="div2" empId="3">
			<percentTime>20</percentTime>
		</WorksFor>
		<WorksFor divId="div3" empId="3">
			<percentTime>20</percentTime>
		</WorksFor>
		<WorksFor divId="div8" empId="3">
			<percentTime>60</percentTime>
		</WorksFor>
	</Employee>
	<Employee empId="4">
		<empName>Anne</empName>
		<empPhone>324-876-3768</empPhone>
		<empOffice>LA</empOffice>
		<WorksFor divId="div1" empId="4">
			<percentTime>60</percentTime>
		</WorksFor>
		<WorksFor divId="div2" empId="4">
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor divId="div3" empId="4">
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor divId="div13" empId="4">
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor divId="div14" empId="4">
			<percentTime>5</percentTime>
		</WorksFor>
	</Employee>
	<Employee empId="5">
		<empName>Ben</empName>
		<empPhone>453-249-3275</empPhone>
		<empOffice>LA</empOffice>
		<WorksFor divId="div2" empId="5">
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor divId="div3" empId="5">
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor divId="div4" empId="5">
			<percentTime>50</percentTime>
		</WorksFor>
		<WorksFor divId="div5" empId="5">
			<percentTime>30</percentTime>
		</WorksFor>
	</Employee>
	<Employee empId="6">
		<empName>Monica</empName>
		<empPhone>935-487-3859</empPhone>
		<empOffice>LA</empOffice>
		<WorksFor divId="div2" empId="6">
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor divId="div3" empId="6">
			<percentTime>10</percentTime>
		</WorksFor>
		<WorksFor divId="div6" empId="6">
			<percentTime>60</percentTime>
		</WorksFor>
		<WorksFor divId="div7" empId="6">
			<percentTime>20</percentTime>
		</WorksFor>
	</Employee>
	<Employee empId="7">
		<empName>Jennifer</empName>
		<empPhone>935-487-3869</empPhone>
		<empOffice>LA</empOffice>
		<WorksFor divId="div7" empId="7">
			<percentTime>90</percentTime>
		</WorksFor>
		<WorksFor divId="div2" empId="7">
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor divId="div3" empId="7">
			<percentTime>5</percentTime>
		</WorksFor>
	</Employee>
	<Employee empId="8">
		<empName>Mary</empName>
		<empPhone>932-487-3859</empPhone>
		<empOffice>LA</empOffice>
		<WorksFor divId="div11" empId="8">
			<percentTime>90</percentTime>
		</WorksFor>
		<WorksFor divId="div2" empId="8">
			<percentTime>5</percentTime>
		</WorksFor>
		<WorksFor divId="div3" empId="8">
			<percentTime>5</percentTime>
		</WorksFor>
	</Employee>
</Company>
